### ISSUE TITLE
KOPS Route53 Private Zone (No Such Host)

### ISSUE THREAD

**Issue by artbaghdasaryan** [eddycharly/terraform-provider-kops#158] opened 2021-03-26 07:50 UTC
In case of deploying the K8S Cluster via `kops_cluter` and the selecting the Private Zone which is created beforehand 
the` kops_cluster_updater` fails as the newly created record `api.CLUSTER-NAME.DNS-ZONE` is not resolvable
We may add a timeout for 5-10 min's as the `terraform apply` fails

**Comment by eddycharly** [comment] 2021-04-11 19:13
I'm not sure where to add the timeout.
The code that applies the cluster is the same code as in kops itself (there's nothing like a loop with a timeout in the kops code).

Am I correct thinking that the tf code you have creates the vpc, the private zone and the cluster ?

If so, do you have a `depends_on` statement from the `kops_cluster_updater` to the private zone ?
Maybe it could help running the updater after the zone is set up and available.

**Comment by artbaghdasaryan** [comment] 2021-04-11 19:29
> I'm not sure where to add the timeout.
> The code that applies the cluster is the same code as in kops itself (there's nothing like a loop with a timeout in the kops code).
> 
> Am I correct thinking that the tf code you have creates the vpc, the private zone and the cluster ?
> 
> If so, do you have a `depends_on` statement from the `kops_cluster_updater` to the private zone ?
> Maybe it could help running the updater after the zone is set up and available.

I even created the zone manually and with `depends_on` it throws the same error.
So the record is created properly but the host which is executing the `nslookup` resolves the `api` IP after2-3 minutes
![image](https://user-images.githubusercontent.com/72495751/114318397-bf410b80-9b1d-11eb-89e3-2e50389cd600.png)

**Comment by artbaghdasaryan** [comment] 2021-04-11 19:30
> > I'm not sure where to add the timeout.
> > The code that applies the cluster is the same code as in kops itself (there's nothing like a loop with a timeout in the kops code).
> > Am I correct thinking that the tf code you have creates the vpc, the private zone and the cluster ?
> > If so, do you have a `depends_on` statement from the `kops_cluster_updater` to the private zone ?
> > Maybe it could help running the updater after the zone is set up and available.
> 
> I even created the zone manually and with `depends_on` it throws the same error.
> So the record is created properly but the host which is executing the `nslookup` resolves the `api` IP after2-3 minutes
> ![image](https://user-images.githubusercontent.com/72495751/114318397-bf410b80-9b1d-11eb-89e3-2e50389cd600.png)

Yes the code creates the VPC,passes the subnet ids to kops provider

**Comment by eddycharly** [comment] 2021-04-11 20:01
Thanks for the additional infos.
At what point the updater fails ? Does it keeps saying `Still creating...` ?

Also, the nat seems to be in the creating state, without the nat up, nodes in private subnets won't be able to start (they need internet access).

**Comment by eddycharly** [comment] 2021-04-11 20:12
I feel like it is an issue with the rolling update attempt.

Does it fail (at creation time) if you skip the rolling update phase ?

```yaml
resource "kops_cluster_updater" "updater" {
  // ....
  rolling_update {
    skip = true
  }
}
```

**Comment by artbaghdasaryan** [comment] 2021-04-11 20:12
> Thanks for the additional infos.
> At what point the updater fails ? Does it keeps saying `Still creating...` ?
> 
> Also, the nat seems to be in the creating state, without the nat up, nodes in private subnets won't be able to start (they need internet access).

It stuck with `module.k8s-cluster.kops_cluster_updater.updater: Still creating... [20s elapsed]`
And then the NAT gateway is up 
`module.vpc.aws_route.private_nat_gateway[2]: Creation complete after 1s [id=r-rtb-07f4bde3c550204251080289494]`
it fails with 
`Error: Get https://<Cluster Name>/api/v1/nodes: dial tcp: lookup api.<Cluster Name> on 10.0.0.2:53: no such host`

**Comment by artbaghdasaryan** [comment] 2021-04-11 20:13
> I feel like it is an issue with the rolling update attempt.
> 
> Does it fail (at creation time) if you skip the rolling update phase ?
> 
> ```terraform
> resource "kops_cluster_updater" "updater" {
>   // ....
> 
>   rolling_update {
>     skip = true
>   }
> }
> ```

Yes
Even I tried the `timeouts`

**Comment by eddycharly** [comment] 2021-04-11 20:22
Strange, i don't think applying the cluster uses the api server.

Rolling update and validation use it. Rolling update does not tolerate the resolve error but validation tolerates it.
With rolling update skipped, it should apply the cluster and move to validation.
Validation could take some time but shouldn't fail.

I'll try to confirm this with the kops maintainers.

**Comment by eddycharly** [comment] 2021-04-12 06:08
I just got confirmed that applying a cluster itself should not be the cause of the error, it's either an issue with rolling update or validation.

Can you please try with both disabled and let me know if the issue happens again ?
```hcl
resource "kops_cluster_updater" "updater" {
  // ....

  rolling_update {
    skip = true
  }

  validation {
    skip = true
  }
}
```

**Comment by artbaghdasaryan** [comment] 2021-04-12 06:14
> I just got confirmed that applying a cluster itself should not be the cause of the error, it's either an issue with rolling update or validation.
> 
> Can you please try with both disabled and let me know if the issue happens again ?
> 
> ```terraform
> resource "kops_cluster_updater" "updater" {
>   // ....
> 
>   rolling_update {
>     skip = true
>   }
> 
>   validation {
>     skip = true
>   }
> }
> ```

It works with this configuration
But now it throws another error

**Comment by artbaghdasaryan** [comment] 2021-04-12 06:14
> > I just got confirmed that applying a cluster itself should not be the cause of the error, it's either an issue with rolling update or validation.
> > Can you please try with both disabled and let me know if the issue happens again ?
> > ```terraform
> > resource "kops_cluster_updater" "updater" {
> >   // ....
> > 
> >   rolling_update {
> >     skip = true
> >   }
> > 
> >   validation {
> >     skip = true
> >   }
> > }
> > ```
> 
> It works with this configuration
> But now it throws another error

`Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable`

**Comment by eddycharly** [comment] 2021-04-12 06:17
At what point do you have the `Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable` error ?

Is this an error with the provider or when trying to use `kubectl` ?

**Comment by artbaghdasaryan** [comment] 2021-04-12 09:50
> At what point do you have the `Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable` error ?
> 
> Is this an error with the provider or when trying to use `kubectl` ?

When running the `terraform apply` second time

**Comment by eddycharly** [comment] 2021-04-12 09:54
The error is bound to the `updater` ?
Did you change the config between first and second apply ?

**Comment by artbaghdasaryan** [comment] 2021-04-12 17:13
> The error is bound to the `updater` ?
> Did you change the config between first and second apply ?

The error is bound to `helm` provider which uses `kubernetes` 

Also another error on the first change after creation


```
When expanding the plan for module.k8s-cluster.kops_cluster.cluster to include
new values learned so far during apply, provider
"registry.terraform.io/eddycharly/kops" produced an invalid new value for
.revision: was cty.NumberIntVal(2), but now cty.NumberIntVal(1).

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
My configuration
```
provider "kubernetes" {
  host                   = data.kops_kube_config.kube_config.server
  username               = data.kops_kube_config.kube_config.kube_user
  password               = data.kops_kube_config.kube_config.kube_password
  client_certificate     = data.kops_kube_config.kube_config.client_cert
  client_key             = data.kops_kube_config.kube_config.client_key
  cluster_ca_certificate = data.kops_kube_config.kube_config.ca_cert
}

provider "helm" {
  kubernetes {
    host                   = data.kops_kube_config.kube_config.server
    username               = data.kops_kube_config.kube_config.kube_user
    password               = data.kops_kube_config.kube_config.kube_password
    client_certificate     = data.kops_kube_config.kube_config.client_cert
    client_key             = data.kops_kube_config.kube_config.client_key
    cluster_ca_certificate = data.kops_kube_config.kube_config.ca_cert
  }
}
```

Error logs for `helm` provider
```
2021-04-12T17:02:21.983Z [INFO]  plugin.terraform-provider-helm_v2.0.3_x5: 2021/04/12 17:02:21 [DEBUG] Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable: timestamp=2021-04-12T17:02:21.983Z
2021-04-12T17:02:21.983Z [INFO]  plugin.terraform-provider-helm_v2.0.3_x5: 2021/04/12 17:02:21 [DEBUG] could not get release Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable: timestamp=2021-04-12T17:02:21.983Z
2021-04-12T17:02:21.983Z [INFO]  plugin.terraform-provider-helm_v2.0.3_x5: 2021/04/12 17:02:21 [DEBUG] [resourceReleaseExists: metrics-server] Done: timestamp=2021-04-12T17:02:21.983Z
2021-04-12T17:02:22.031Z [INFO]  plugin.terraform-provider-kubernetes_v2.0.3_x5: 2021/04/12 17:02:22 [WARN] Invalid provider configuration was supplied. Provider operations likely to fail: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable: timestamp=2021-04-12T17:02:22.031Z

Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

And if I set ENV variable `export KUBE_CONFIG_PATH=~/.kube/config` and rerun the apply it executes without error

**Comment by eddycharly** [comment] 2021-04-12 19:00
The way you use `data.kops_kube_config` looks okay, i use it exactly the same as you.

> And if I set ENV variable `export KUBE_CONFIG_PATH=~/.kube/config` and rerun the apply it executes without error

This should not be set, this is why `data.kops_kube_config` exists, there's no need to have the config set up in the kubeconfig file.

The error regarding the `revision` looks strange, it is a computed value and it looks like the value changed between plan and apply.

How do you declare your `data.kops_kube_config.kube_config` ?
Does it depends on your `updater` or `cluster` resource ?

**Comment by artbaghdasaryan** [comment] 2021-04-13 06:11
> The way you use `data.kops_kube_config` looks okay, i use it exactly the same as you.
> 
> > And if I set ENV variable `export KUBE_CONFIG_PATH=~/.kube/config` and rerun the apply it executes without error
> 
> This should not be set, this is why `data.kops_kube_config` exists, there's no need to have the config set up in the kubeconfig file.
> 
> The error regarding the `revision` looks strange, it is a computed value and it looks like the value changed between plan and apply.
> 
> How do you declare your `data.kops_kube_config.kube_config` ?
> Does it depends on your `updater` or `cluster` resource ?

```
data "kops_kube_config" "kube_config" {
  cluster_name = kops_cluster.cluster.name
  depends_on   = [kops_cluster_updater.updater]
}
```

**Comment by eddycharly** [comment] 2021-04-13 11:39
I’m finalising the alpha support for 1.19 today.
I will swap validation and rolling update order, hopefully it should help.
Will you be able to test it ?

**Comment by artbaghdasaryan** [comment] 2021-04-13 11:59
> I’m finalising the alpha support for 1.19 today.
> I will swap validation and rolling update order, hopefully it should help.
> Will you be able to test it ?

Sure. Please let me know when You are done

**Comment by eddycharly** [comment] 2021-04-14 18:47
You can try the `1.19.0-alpha.6` provider.
Beware that there are a few issues with kops and calico though (https://github.com/kubernetes/kops/pull/11203) that can potentially be hard to workaround.

**Comment by artbaghdasaryan** [comment] 2021-04-15 06:44
> You can try the `1.19.0-alpha.6` provider.
> Beware that there are a few issues with kops and calico though ([kubernetes/kops#11203](https://github.com/kubernetes/kops/pull/11203)) that can potentially be hard to workaround.

Can You share the example to enable `addons` as it is not documented yet ?

**Comment by eddycharly** [comment] 2021-04-15 07:33
Do you mean addons like clusterautoscaler ?
You have to enable it in the cluster resource, see the docs https://registry.terraform.io/providers/eddycharly/kops/latest/docs/resources/cluster#cluster_autoscaler_config

**Comment by eddycharly** [comment] 2021-04-15 07:34
Probably adding something like this:
```hcl
cluster_autoscaler {
  enabled = true
}
```

**Comment by artbaghdasaryan** [comment] 2021-04-15 07:45
> Probably adding something like this:
> 
> ```terraform
> cluster_autoscaler {
>   enabled = true
> }
> ```

And which addons it will enable ?

**Comment by artbaghdasaryan** [comment] 2021-04-15 07:49
> > Probably adding something like this:
> > ```terraform
> > cluster_autoscaler {
> >   enabled = true
> > }
> > ```
> 
> Thanks will try

It is not working
```
│ Error: Missing required argument
│
│   on ../terraform-modules/k8s/kops_cluster.tf line 12, in resource "kops_cluster" "cluster":
│   12:     addons  {
│
│ The argument "manifest" is required, but no definition was found.
╵
╷
│ Error: Unsupported argument
│
│   on ../terraform-modules/k8s/kops_cluster.tf line 13, in resource "kops_cluster" "cluster":
│   13:     cluster_autoscaler = {
│
│ An argument named "cluster_autoscaler" is not expected here.
╵
╷
│ Error: Unsupported argument
│
│   on ../terraform-modules/k8s/kops_cluster.tf line 16, in resource "kops_cluster" "cluster":
│   16:     cert_manager = {
│
│ An argument named "cert_manager" is not expected here.
╵
```

**Comment by artbaghdasaryan** [comment] 2021-04-15 07:59
Maybe only `cluster_autoscaler` addon is supported in this alpha version ,and I wanted to add the `cert-manager` as well

**Comment by eddycharly** [comment] 2021-04-15 08:00
It's not a named argument but a nested struct, you shouldn't have an `=` sign. (no `cluster_autoscaler = `)

**Comment by eddycharly** [comment] 2021-04-15 08:07
You don't need the `addons` stanza too.
Try something like this:
```hcl
resource "kops_cluster" "cluster" {
  // usual config here....

  // enable cluster autoscaler
  cluster_autoscaler {
    enabled = true
  }
}
```

**Comment by artbaghdasaryan** [comment] 2021-04-15 08:17
> You don't need the `addons` stanza too.
> Try something like this:
> 
> ```terraform
> resource "kops_cluster" "cluster" {
>   // usual config here....
> 
>   // enable cluster autoscaler
>   cluster_autoscaler {
>     enabled = true
>   }
> }
> ```

Thanks it works now, just to double check if `cert-manager` addon will be added or I will go on with `helm-chart` ?

**Comment by eddycharly** [comment] 2021-04-15 08:28
It is, everything kops 1.19.2 supports should be supported. 
look at the docs link I sent you in the previous message.

**Comment by eddycharly** [comment] 2021-05-06 18:11
@artbaghdasaryan is there something i can do to help you or shall i close the issue ?

**Comment by artbaghdasaryan** [comment] 2021-05-07 05:40
> @artbaghdasaryan is there something i can do to help you or shall i close the issue ?

Hey @eddycharly 
Thanks for prompt support
We can close the issue

**Comment by eddycharly** [comment] 2021-05-07 06:39
👍

**Closed by eddycharly** 2021-05-07 06:39 UTC
